#ifndef MIKROCONTROLLER_LICHTORGEL_UI_CONSTANTS_H
#define MIKROCONTROLLER_LICHTORGEL_UI_CONSTANTS_H

#define DEFAULT_TEXT_COLOR C_WHITE
#define DEFAULT_BACKGROUND_COLOR C_BLACK
#define FRAME_COLOR_UNFOCUSED C_BLUE
#define FRAME_COLOR_FOCUSED C_RED

#define CHAR_SIZE 10
#define BORDER_SIZE 2
#define TICK_LENGTH 2

#endif //MIKROCONTROLLER_LICHTORGEL_UI_CONSTANTS_H
