#ifndef MIKROCONTROLLER_LICHTORGEL_GLOBAL_CONSTANTS_H
#define MIKROCONTROLLER_LICHTORGEL_GLOBAL_CONSTANTS_H

#define FFT_SIZE 512
#define LED_COUNT 126

#endif //MIKROCONTROLLER_LICHTORGEL_GLOBAL_CONSTANTS_H
