// MP3 data type : STEREO
// MP3 samplerate: 44100
//
// This file was generated by mp3pcm2cpp, a small
// program to convert a MP3 file into a raw binary
// data file or a C/C++ struct of PCM values.
//
//  Source file was: D:/Fachhochschule/Semester5/MikrocontrollerTechnik/Projekte/mct-projekt/sounds/cinematic-synth-riser.mp3
//
#include <cstdint>

extern const uint16_t cinematic_synth_riser[89856];
